sampletable: 'config/sampletable.tsv'
patterns: 'config/patterns.yaml'
data_dir: '../data/Data_20160817'
output_dir: '../output/pacbio-wf'
fasta: '../lcdb-references/dmel/r6-11/fasta/dmel_r6-11.fasta'
gtf: '../lcdb-references/dmel/r6-11/gtf/dmel_r6-11.gtf'
